# How to get unique array elements

In [3]:
import numpy as np
np.unique(np.random.randint(0,255,size=(10,)))

array([ 26,  69,  82,  94, 130, 147, 149, 151, 155, 212])

With counts for each values:

In [6]:
np.unique(np.random.randint(0,255,size=(10,)), return_counts=True)

(array([ 70, 106, 113, 116, 117, 179, 185, 196, 210, 227]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

## Bonus : using pandas

In [5]:
import pandas
df = pandas.DataFrame(np.random.randint(0,255,size=(10,)) , columns=["test"])
print(pandas.unique(df.test))

[217 232 146 226 179 254 135 181 105 188]
